// File generated by FlutterFire CLI for Firebase project: workgo-sih2026
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// [WorkGoFirebaseOptions] provides default Firebase options for all WorkGo apps.
class WorkGoFirebaseOptions {
  static const String projectId = 'workgo-sih2026';
  static const String storageBucket = 'workgo-sih2026.firebasestorage.app';
  static const String messagingSenderId = '793078865015';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.macOS:
        return ios;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRKAoRw44PuNYMMGQsU0nplvY7MwAnOr4',
    appId: '1:793078865015:web:ecef8ee7cfabcf4bf0fa72',
    messagingSenderId: messagingSenderId,
    projectId: projectId,
    authDomain: 'workgo-sih2026.firebaseapp.com',
    storageBucket: storageBucket,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHs5v4PNWRIDf6T6FcbXucoydpno6uWQM',
    appId: '1:793078865015:android:76ce87a9d688e350f0fa72',
    messagingSenderId: messagingSenderId,
    projectId: projectId,
    storageBucket: storageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwDSFay0ozOp5vz3QJsN7ZCdqyVx0U3X0',
    appId: '1:793078865015:ios:a5ead4da67d53817f0fa72',
    messagingSenderId: messagingSenderId,
    projectId: projectId,
    storageBucket: storageBucket,
    iosBundleId: 'com.workgo.workgoCustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRKAoRw44PuNYMMGQsU0nplvY7MwAnOr4',
    appId: '1:793078865015:web:428bdf84b4108161f0fa72',
    messagingSenderId: messagingSenderId,
    projectId: projectId,
    authDomain: 'workgo-sih2026.firebaseapp.com',
    storageBucket: storageBucket,
  );
}
