const { detectSyntheticImage } = require("../src/services/synthetic_image_detector");

describe("Synthetic Image Detector & Anti-Spoofing Unit Tests", () => {
  it("should pass standard clean image buffer", () => {
    // Simulated clean JPEG with camera EXIF header
    const mockCleanJpeg = Buffer.concat([
      Buffer.from([0xff, 0xd8, 0xff, 0xe1]),
      Buffer.from("Exif\0\0"),
      Buffer.alloc(2000, 0xaa),
    ]);

    const result = detectSyntheticImage(mockCleanJpeg);
    expect(result.isSuspicious).toBe(false);
    expect(result.riskScore).toBeLessThan(0.4);
    expect(result.recommendation).toBe("PASS");
  });

  it("should flag images containing Midjourney / Stable Diffusion metadata", () => {
    const aiMetadataBuffer = Buffer.concat([
      Buffer.from([0xff, 0xd8, 0xff, 0xe1]),
      Buffer.from("Prompt: Portrait of an Indian electrician, generated by Midjourney v6 photorealistic"),
      Buffer.alloc(1000, 0x55),
    ]);

    const result = detectSyntheticImage(aiMetadataBuffer);
    expect(result.isSuspicious).toBe(true);
    expect(result.flags.some((f) => f.includes("midjourney"))).toBe(true);
    expect(result.riskScore).toBeGreaterThanOrEqual(0.4);
    expect(["FLAG_FOR_MANUAL_SCRUTINY", "REJECT_SYNTHETIC_IMAGE"]).toContain(result.recommendation);
  });

  it("should flag PNG containing Stable Diffusion parameter chunks", () => {
    const sdPngBuffer = Buffer.concat([
      Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
      Buffer.from("tEXtparameters\0steps: 30, sampler: DPM++ 2M Karras, cfg scale: 7, seed: 18293849"),
      Buffer.alloc(1000, 0x12),
    ]);

    const result = detectSyntheticImage(sdPngBuffer);
    expect(result.isSuspicious).toBe(true);
    expect(result.flags).toContain("STABLE_DIFFUSION_PROMPT_METADATA_IN_PNG");
    expect(result.recommendation).toBe("REJECT_SYNTHETIC_IMAGE");
  });

  it("should reject empty or invalid payload", () => {
    const result = detectSyntheticImage(null);
    expect(result.isSuspicious).toBe(true);
    expect(result.recommendation).toBe("REJECT_EMPTY_IMAGE");
  });
});
