const crypto = require("crypto");

/**
 * Known AI generative model signatures, diffusion tool keywords, and deepfake generator markers
 */
const AI_GENERATOR_KEYWORDS = [
  "midjourney",
  "dall-e",
  "dalle",
  "stable diffusion",
  "stablediffusion",
  "comfyui",
  "novelai",
  "automatic1111",
  "civitai",
  "invokeai",
  "deepface",
  "faceswap",
  "roop",
  "reactor",
  "generated by",
  "generative fill",
  "adobe firefly",
  "photoshop generative",
  "canvas ai",
  "imagen",
  "synthetic",
  "flux.1",
];

/**
 * Analyzes an uploaded base64 image or buffer for synthetic AI generation markers,
 * manipulated metadata, and camera hardware provenance.
 *
 * @param {string|Buffer} imageInput - Base64 image string or raw Buffer
 * @param {string} [mimeType] - Optional mime type (e.g. image/jpeg, image/png)
 * @returns {Object} Inspection result with risk score, detected flags, and recommendations
 */
function detectSyntheticImage(imageInput, mimeType = "image/jpeg") {
  const flags = [];
  let riskScore = 0.0;
  const detectedKeywords = [];

  if (!imageInput) {
    return {
      isSuspicious: true,
      riskScore: 1.0,
      flags: ["EMPTY_IMAGE_PAYLOAD"],
      recommendation: "REJECT_EMPTY_IMAGE",
    };
  }

  const rawBuffer = Buffer.isBuffer(imageInput)
    ? imageInput
    : Buffer.from(imageInput.replace(/^data:image\/\w+;base64,/, ""), "base64");

  if (rawBuffer.length < 512) {
    return {
      isSuspicious: true,
      riskScore: 0.9,
      flags: ["PAYLOAD_TOO_SMALL_FOR_REAL_CAMERA_IMAGE"],
      recommendation: "FLAG_FOR_MANUAL_SCRUTINY",
    };
  }

  // 1. Text & Metadata Scan for AI Signatures in Image Chunks (EXIF / XMP / PNG Chunks / IPTC)
  const rawString = rawBuffer.toString("latin1").toLowerCase();

  for (const keyword of AI_GENERATOR_KEYWORDS) {
    if (rawString.includes(keyword)) {
      detectedKeywords.push(keyword);
      flags.push(`GENERATIVE_AI_MARKER_DETECTED: "${keyword}"`);
      riskScore += 0.45;
    }
  }

  // 2. Format specific chunk analysis
  const isJpeg = rawBuffer.length > 3 && rawBuffer[0] === 0xff && rawBuffer[1] === 0xd8;
  const isPng = rawBuffer.length > 4 && rawBuffer[0] === 0x89 && rawBuffer[1] === 0x50 && rawBuffer[2] === 0x4e && rawBuffer[3] === 0x47;

  if (isPng) {
    // Check for PNG text chunks often used by Stable Diffusion (tEXt, iTXt parameters)
    if (rawString.includes("parameters") && (rawString.includes("steps:") || rawString.includes("sampler:") || rawString.includes("cfg scale:"))) {
      flags.push("STABLE_DIFFUSION_PROMPT_METADATA_IN_PNG");
      riskScore += 0.7;
    }
  }

  if (isJpeg) {
    // Check for standard EXIF markers
    const hasExif = rawBuffer.includes(Buffer.from("Exif\0\0"));
    if (!hasExif && rawBuffer.length > 200000) {
      // Large JPEG without any EXIF camera info might be an exported render
      flags.push("STRIPPED_EXIF_OR_NON_CAMERA_ORIGIN");
      riskScore += 0.15;
    }
  }

  // 3. Cryptographic integrity hash
  const imageHash = crypto.createHash("sha256").update(rawBuffer).digest("hex");

  // Normalize score between 0.0 and 1.0
  riskScore = Math.min(1.0, Math.max(0.0, riskScore));
  const isSuspicious = riskScore >= 0.4;

  let recommendation = "PASS";
  if (riskScore >= 0.7) {
    recommendation = "REJECT_SYNTHETIC_IMAGE";
  } else if (riskScore >= 0.4) {
    recommendation = "FLAG_FOR_MANUAL_SCRUTINY";
  }

  return {
    isSuspicious,
    riskScore: Number(riskScore.toFixed(2)),
    flags,
    detectedKeywords,
    imageHash,
    byteSize: rawBuffer.length,
    recommendation,
    inspectedAt: new Date().toISOString(),
  };
}

module.exports = {
  detectSyntheticImage,
  AI_GENERATOR_KEYWORDS,
};
