// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRKAoRw44PuNYMMGQsU0nplvY7MwAnOr4',
    appId: '1:793078865015:web:ecef8ee7cfabcf4bf0fa72',
    messagingSenderId: '793078865015',
    projectId: 'workgo-sih2026',
    authDomain: 'workgo-sih2026.firebaseapp.com',
    storageBucket: 'workgo-sih2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHs5v4PNWRIDf6T6FcbXucoydpno6uWQM',
    appId: '1:793078865015:android:76ce87a9d688e350f0fa72',
    messagingSenderId: '793078865015',
    projectId: 'workgo-sih2026',
    storageBucket: 'workgo-sih2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwDSFay0ozOp5vz3QJsN7ZCdqyVx0U3X0',
    appId: '1:793078865015:ios:a5ead4da67d53817f0fa72',
    messagingSenderId: '793078865015',
    projectId: 'workgo-sih2026',
    storageBucket: 'workgo-sih2026.firebasestorage.app',
    iosBundleId: 'com.workgo.workgoCustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRKAoRw44PuNYMMGQsU0nplvY7MwAnOr4',
    appId: '1:793078865015:web:428bdf84b4108161f0fa72',
    messagingSenderId: '793078865015',
    projectId: 'workgo-sih2026',
    authDomain: 'workgo-sih2026.firebaseapp.com',
    storageBucket: 'workgo-sih2026.firebasestorage.app',
  );
}
